- name: "spinning up a new cluster"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy new client0 ;
  ignore_errors: yes

- name: "overwriting ceph.conf part0"
  copy: src="{{ ceph_deploy_ansible_path }}/ceph_conf/{{ ceph_conf }}"
        dest="{{ local_home }}/cluster"
        mode=preserve

- name: "overwriting ceph.conf part1"
  shell: |
    cd "{{ local_home }}/cluster" ;
    mv ceph.conf ceph.conf_default ;
    cat ceph.conf_default >> ceph.conf ;
    cat {{ ceph_conf }} >> ceph.conf ;
    chmod '777' ceph.conf ;

- name: "changing deploy log permissions"
  shell: |
    cd "{{ local_home }}/cluster" ;
    chmod '777' ceph-deploy-ceph.log ;

- name: "spinning up a new monitor"
  shell: |
    cd "{{ local_home }}/cluster" ;
    sudo chmod 766 *.keyring ;
    env/bin/ceph-deploy --overwrite-conf mon create client0 ;
    sudo chmod 766 *.keyring ;
    env/bin/ceph-deploy gatherkeys client0 ;
    sudo chmod 766 *.keyring ;

- name: "zap+create disks"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy osd create {{ item }}:{{ osd_device_path }} ;
    sudo chmod 766 *.keyring ;
  with_inventory_hostnames:
    - osds

- name: "spin up admin"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy admin client0 ;
    sudo chmod a+r /etc/ceph/ceph.client.admin.keyring ;
    sudo chmod 766 *.keyring ;

- name: "push configs to osds"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy config push {{ item }} ;
    sudo chmod 766 *.keyring ;
  with_inventory_hostnames:
    - osds

- name: "spin up mgr"
  shell: |
    cd "{{ local_home }}/cluster" ;
    env/bin/ceph-deploy mgr create client0 ;
    sudo chmod 766 *.keyring ;
