---
- hosts: all
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - ./vars/extra_vars.yml
  roles:
    - basic

- hosts: clients
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - ./vars/extra_vars.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - clients

# self-validation
- hosts: clients
  gather_facts: false
  become: True
  any_errors_fatal: true
  post_tasks:
    - name: "get ceph status from the first monitor"
      command: ceph -s
      changed_when: false
      delegate_to: client0
      run_once: true
