---
- hosts: all
  vars_files:
    - ./vars/extra_vars.yml
  roles:
    - basic

- hosts: clients
  vars_files:
    - ./vars/extra_vars.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - clients

- hosts: osds
  vars_files:
    - ./vars/extra_vars.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - osds

- hosts: all
  vars_files:
    - ./vars/extra_vars.yml
  roles:
    - final

#- hosts: clients
#  vars_files:
#    - ./vars/extra_vars.yml
#  tasks:
#  - name "self-validate"
#      shell: |
#        cd "{{ local_home }}" ;
#        python validate.py res_select_all.out res_select_all.txt ;
#        python validate.py res_project_cols.out res_project_cols.txt ;
#        python validate.py res_sum.out res_sum.txt ;
